spring:
  flyway:
    schemas: infobip-uri-shortener
    url: jdbc:h2:mem:infobip;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: sa
    password: password
  datasource:
    data: classpath:data.sql
    initialization-mode: always
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    #defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    com: INFO
